<script setup lang="ts" generic="PayloadType extends object">
import { usePointer, useEventListener } from "@vueuse/core";
import {
  ref,
  toRaw,
  onMounted,
  watch,
  computed,
  Ref,
  TransitionProps,
} from "vue";
import { useMovingItem } from "./useMovingItem.js";
import PointerElement from "./PointerElement.vue";
import { type MovingItem } from "./types.js";

export type ArrangeableOptions = {
  hoverClass?: string;
  pickedItemClass?: string;
  unpickedItemClass?: string;
  listTransition?: TransitionProps;
  hoverTransition?: TransitionProps;
  handle?: boolean;
};

type ArrangeableProps<T> = {
  options?: ArrangeableOptions;
  list: T[];
  // Can we use an inferred key here, as in keyof PayloadType? It throws weird errors below.
  listKey?: string;
  name?: string | symbol;
  group?: string | symbol;
  targets?: string | symbol | Array<string | symbol>;
};

const props = withDefaults(defineProps<ArrangeableProps<PayloadType>>(), {
  name: Symbol(),
  options: () => ({
    hoverClass: "",
    hoverTransition: {},
    pickedItemClass: "",
    unpickedItemClass: "",
    listTransition: {},
  }),
});

type KeyItem = {
  payload: PayloadType;
  key: any;
};

const { movingItem, isMoving } = useMovingItem<PayloadType>();
const hoverElement = ref<HTMLElement>();
// https://github.com/vuejs/core/issues/2136#issuecomment-908269949
const keyItemsList = ref<KeyItem[]>([]) as Ref<KeyItem[]>;
const arrangedItems = computed(
  () => keyItemsList.value.map(({ payload }) => payload) || []
);

function populateList(listData: PayloadType[]) {
  const newList: KeyItem[] = [];
  // Make sure to preserve the keys associated with the objects, whether autogenerated or supplied:
  listData.forEach((item: any) => {
    const keyItem = props.listKey
      ? keyItemsList.value.find(
          ({ key }) => key === item[props.listKey as string]
        )
      : keyItemsList.value.find(({ payload }) => item === payload);
    if (keyItem) newList.push({ ...keyItem, payload: item });
    else
      newList.push({
        key:
          props.listKey && Object.keys(item).includes(props.listKey)
            ? item[props.listKey]
            : Symbol(),
        payload: item,
      });
  });
  keyItemsList.value = newList;
}

watch(() => props.list, populateList);

const emit = defineEmits<{
  (e: "liftItem", item: MovingItem<PayloadType>): void;
  (e: "dropItem", item: MovingItem<PayloadType>): void;
}>();

/**
 * triggered when the mouse cursor enters a list item while dragging something.
 * @param index: index of the item hovered over.
 */
const hoverOverItem = (index: number) => {
  enterList();
  if (
    !movingItem.value ||
    movingItem.value?.destination !== props.name ||
    isMoving(arrangedItems.value[index])
  ) {
    return;
  }
  movingItem.value.toIndex = index;
  // if the dragging item does not appear in the list, add it
  if (!arrangedItems.value?.includes(movingItem.value.payload)) {
    keyItemsList.value.splice(index, 0, {
      payload: movingItem.value.payload,
      key: movingItem.value.key,
    });
  }
  // else move it
  else {
    const moverIndex = keyItemsList.value.findIndex(
      ({ payload }) => payload === movingItem.value?.payload
    );
    keyItemsList.value =
      moverIndex < index
        ? [
            ...keyItemsList.value.slice(0, moverIndex),
            ...keyItemsList.value.slice(moverIndex + 1, index + 1),
            keyItemsList.value[moverIndex],
            ...keyItemsList.value.slice(index + 1),
          ]
        : [
            ...keyItemsList.value.slice(0, index),
            keyItemsList.value[moverIndex],
            ...keyItemsList.value.slice(index, moverIndex),
            ...keyItemsList.value.slice(moverIndex + 1),
          ];
  }
};

// https://play.vuejs.org/#eNrdVk1v4zYQ/SsDLYooiSXZySYH1THSS4sFWrRAe2ix2gMtUTZriRREyonXyH/vIynb8kdz2tMmAUQO33AeZx6H2QY/NU287niQBlOdt6IxpLnpmlkmRd2o1tCWWl7SG5WtqukK0Kv90p/4VvxXoU2/GicHk931AP25k6vNEXJv6YFEmcyVBGLBzScpjGDVJ8NrTU8UXtPTjD5PRnQ3ovsRfRzRw5cdXPQg0AxPXMPr60xWHJgCAAeM16zqeFxxuTBLuqVJJjNZdjI3QkkSUvPWINzWEur3h+tvzCzjVnWyCP2QyULVwN1c2BUx6cism0rkPBQjGo9A5fYWiLejuC1H1ndhB64IfXakU1+97Mqy4pe9BzO7SBTXrAmt1WY03LqV1MFGpFGptD9rf8A3m0HnZxfDkI1o7orBnIEimruBQ2XG7W7nHAmfuQ154cNf/3h+6FqtkRbEPkv4MH1CFvz199ID3RFLCgXNKJr0fv+X7omDIyr+ponXN5SNCeBNxQzHjGg674wBoeccjqunLPAyyIKZHxAz5BMCgYDLNPEOl51dLeHrvu9D+9IB3I+O4YdLk7rzWWb2mwW0jnSlDAxbd3ScMXA+mZkWYu2G9me7W0YCvOUC3UMVsMnfewr2QjqPZLfj9HBpMZ8mgyRmMhgF/q5H0ED8r1YSPcVVB6zdAninu3plAW69nWfB0phGp0nSyWa1iHNVJ89YS9pOGlHzCFl/vo/v4o8P4KHN0B5zXUfzVr2gSIiYBaPB5gmMa95GLUfJWt6+G+wEexTwZO0s6E5iSMBRT7vQUgteCsn/aFWjw8/W78rVE93vC5T6nkL/gv40uoCSv6ANNSRZzVG8khVWPX2hUCcIo1RtLxSo1V8MCCavmN4JCNN0xTf72V4uR9rB1GrMa+/gmeyFMZTGsUxO2J6LZarNprJDlEAahqS0XhmN8n4pugPQYs3RNmBmRSHkIqXxrovE7oDO50UUZpnSZDz+wYGXXCyWaGT34+bVGeYsXy1c945yVak2pQ/lvf31q6pFYeHfvKJhVXgqPjw+PvZLr5EWX11kD4tg2lFIbmgSU8GR2paT2Z+ZbhLws6WJ7NWCKP2ES4MNGJrfwFhxtua90R/nsFFKrKpoHD9oyru5yKM5/yp4G8Ly4N6ScYwncbLvrCB0dyDkwvnnFr2LXCAyirRBFQYcPS2LOyEFrCOkGpYLs/HJ7/lBZHVKOmcV/wd8xujEzm4rHNrEg9yQ130MProDLbs3Eto/2y5zbMUlqc6QKqliGzsqK/WCapBZovcii/DYiY7hfwooA08F5UzSnONT5Z2NXOAFaVuem2oTD054nuODzNgcNe+MlZl/JJwwcZeP/5P5lpcZFvNtbiy6/YUrOkNsWM/u5fd4C/cFe/sPiY2qXQ==

const leaveList = () => {
  if (movingItem.value !== undefined) {
    // N.b. if the v-for list inside the transitiongroup has a ref with a ref() constant in the setup function,
    // leaving the list will go clunky. https://github.com/vuejs/core/issues/8173
    const itemIndex = arrangedItems.value.indexOf(movingItem.value.payload);
    if (itemIndex >= 0) {
      keyItemsList.value.splice(itemIndex, 1);
    }
    movingItem.value.destination = undefined;
    movingItem.value.toIndex = undefined;
  }
};

const enterList = () => {
  if (
    movingItem.value &&
    (movingItem.value.targets.includes(props.name) ||
      (props.group && movingItem.value.targets.includes(props.group)))
  ) {
    movingItem.value.destination = props.name;
    movingItem.value.destinationList = arrangedItems.value;
  }
};

let offsetX: number = 0;
let offsetY: number = 0;
const liftItem = ($event: PointerEvent, { key, payload }: KeyItem) => {
  if (
    props.options?.handle &&
    ($event.target as Element).attributes.getNamedItem("name")?.value !==
      "handle"
  )
    return;
  const targetBox = ($event.currentTarget as Element)?.getBoundingClientRect();
  offsetX = pointer.x.value - targetBox.x;
  offsetY = pointer.y.value - targetBox.y;
  movingItem.value = {
    payload,
    hoverElement,
    origin: props.name,
    originList: arrangedItems.value,
    destination: props.name,
    destinationList: arrangedItems.value,
    fromIndex: arrangedItems.value.indexOf(payload),
    toIndex: arrangedItems.value.indexOf(payload),
    targets: [props.targets ?? props.group ?? props.name].flat(),
    originItemBoundingBox: targetBox,
    key,
  };
  emit("liftItem", toRaw(movingItem.value));
};

/**
 * dropItem happens when an element from this ArrangedList is dropped.
 * N.b. this is NOT triggered when an element from another list is dropped onto this one.
 */
const dropItem = () => {
  if (movingItem.value === undefined || movingItem.value.origin !== props.name)
    return;
  emit("dropItem", toRaw(movingItem.value));
  // repopulation is needed in case the drop event did not trigger a props change
  // otherwise the dropped item disappears.
  populateList(props.list);
  movingItem.value = undefined;
};

const pointer = usePointer();
useEventListener(document, "pointerup", dropItem);

const beforeKey = Symbol();
const afterKey = Symbol();

defineExpose({
  arrangedItems,
  name: props.name,
});

onMounted(() => {
  populateList(props.list);
  document.body.style.touchAction = "none";
});
</script>

<template>
  <PointerElement @pointer-leave="leaveList" @pointer-enter="enterList">
    <TransitionGroup v-bind="options.listTransition">
      <div :key="beforeKey">
        <slot name="before" :arrangedItems="arrangedItems" />
      </div>
      <PointerElement
        v-for="(item, index) in keyItemsList || []"
        :key="item.key"
        :class="
          isMoving(item.payload)
            ? options.pickedItemClass
            : options.unpickedItemClass
        "
        @pointerdown.left.prevent="liftItem($event, item)"
        @pointer-enter="hoverOverItem(index)"
      >
        <slot
          :item="item.payload as PayloadType"
          :arrangedItems="arrangedItems"
        />
      </PointerElement>
      <div :key="afterKey">
        <slot name="after" :arrangedItems="arrangedItems" />
      </div>
    </TransitionGroup>
    <Teleport to="body">
      <div
        v-if="movingItem && movingItem.origin === name"
        ref="hoverElement"
        :style="{
          left: pointer.x.value - offsetX + 'px',
          top: pointer.y.value - offsetY + 'px',
        }"
        style="z-index: 100000000; position: fixed"
        :class="options.hoverClass"
      >
        <slot :item="movingItem.payload" />
      </div>
    </Teleport>
  </PointerElement>
</template>
